### ISSUE TITLE
Heads up

### ISSUE THREAD

**Issue by thiagof** [brandonhimpfen/wordpress-bootstrap-css#1]
Did you implemented any sort of customization in Twtter Bootstrap to improve usage in WP-Admin?

**Comment by brandonhimpfen** [comment]
- Not sure why this is a heads up;
- This project is not designed to improve the "usage" in the WordPress dashboard;
- This project is for using Bootstrap CSS within the dashboard;
- This project has not yet started - there are no commits of files.

**Comment by thiagof** [comment]
yes I know and seen there were no commits...
was just asking for advice. thank you!!

2015-03-27 11:54 GMT-03:00, Brandon Himpfen <notifications@github.com>:
> - Not sure why this is a heads up;
> - This project is not designed to improve the "usage" in the WordPress
> dashboard;
> - This project is for using Bootstrap CSS within the dashboard;
> - This project has not yet started - there are no commits of files.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/brandonhimpfen/wordpress-bootstrap-css/issues/1#issuecomment-86963467


-- 
*Thiago Fernandes*
Analista de Processos
34 9176- 4055 | thiago@internetbudi.com.br
